// <auto-generated />
using System;
using CodeSec.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeSec.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeSec.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartmentName");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CodeSec.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartmentId");

                    b.Property<string>("EmployeeName");

                    b.Property<string>("RoleTitle");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CodeSec.Models.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PictureName");

                    b.Property<int>("SickNoteId");

                    b.HasKey("PictureId");

                    b.HasIndex("SickNoteId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("CodeSec.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SampleName");

                    b.Property<int>("SickNoteId");

                    b.HasKey("SampleId");

                    b.HasIndex("SickNoteId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("CodeSec.Models.Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentValue");

                    b.HasKey("Id");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("CodeSec.Models.SickNote", b =>
                {
                    b.Property<int>("SickNoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Certificate");

                    b.Property<DateTime>("DateOfSickness");

                    b.Property<string>("DepartmentId");

                    b.Property<string>("EmployeeId");

                    b.Property<string>("EmployeeName")
                        .IsRequired();

                    b.Property<string>("EmployeePhone")
                        .IsRequired();

                    b.Property<string>("Other");

                    b.Property<string>("RefNumber");

                    b.Property<string>("RegularEmployeeAction");

                    b.Property<string>("RegularEmployeeInfo");

                    b.Property<string>("StatusId");

                    b.Property<string>("TypeOfSickness")
                        .IsRequired();

                    b.HasKey("SickNoteID");

                    b.ToTable("SickNotes");
                });

            modelBuilder.Entity("CodeSec.Models.SickNoteStatus", b =>
                {
                    b.Property<string>("StatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StatusName");

                    b.HasKey("StatusId");

                    b.ToTable("SickNoteStatuses");
                });

            modelBuilder.Entity("CodeSec.Models.Picture", b =>
                {
                    b.HasOne("CodeSec.Models.SickNote")
                        .WithMany("Pictures")
                        .HasForeignKey("SickNoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CodeSec.Models.Sample", b =>
                {
                    b.HasOne("CodeSec.Models.SickNote")
                        .WithMany("Samples")
                        .HasForeignKey("SickNoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
